name: Deploy Testnet

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag for the release'
        required: true
      release:
        description: 'Name of this release'
        required: true        
jobs: 
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v4
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.tag }}
          release_name: ${{ github.event.inputs.tag }}
          draft: false
          prerelease: false
  build_binaries:
    name: build_binaries
    runs-on: ubuntu-latest
    # Fetch an OpenID Connect (OIDC) token. This requires id-token: write. For more information, see "About security hardening with OpenID Connect"
    permissions:
      id-token: write
      contents: read
    steps:
      - name: INstall dependencies
        run: |
            sudo apt install jq -y
      - name: Checkout Tag
        uses: actions/checkout@v4
        with:
          repository: MariosAronis/evmos-WIP
          ref: ${{ github.event.inputs.tag }}
          persist-credentials: false
      - name: Build evmosd
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
          check-latest: true
      - run: |
          make build
      - name: Upload binary
        uses: actions/upload-artifact@v3
        with:
          name: "evmosd-${{ github.event.inputs.tag }}"
          path: /home/runner/work/evmos-WIP/evmos-WIP/build/evmosd
      - name: Configure AWS short lived credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::044425962075:role/evmos-testnet-deploy-slc
          role-duration-seconds: 900
          aws-region: us-west-2
      - name: Upload binary to S3
        run: |
            aws s3 cp /home/runner/work/evmos-WIP/evmos-WIP/build/evmosd/evmosd-${{ github.event.inputs.tag }} s3://evmosd-binaries          
      - name: Deploy release to testnet nodes
        run: |
            .github/scripts/deploy_testnet.sh
          


